### PR TITLE
Makefile: refactor is-git-repo inclusion logic

### PR DESCRIPTION
**Pull request by apjanke**
Here's a suggestion for refactoring the Makefile to simplify it. This avoids the need for a big repeated block of code for the command-construction logic, where the two blocks differ by only one line.

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by apjanke** [comment]
Thanks!

**Comment by nicolaiskogheim** [comment]
Sweet!

**Comment by dwijnand** [comment]
This patch does the wrong thing. `COMMANDS_USED_WITHOUT_GIT_REPO` doesn't mean "commands that use is_git_repo, and should have it included in the "built" version of the command".

For fallout see #493.

**Comment by apjanke** [comment]
Oh, jeez. Sorry about that. Here's a PR that fixes the sense of the test: #494

**Pull request merged**
