### PR TITLE
Fix git-changelog for compatibility for bash<4. Fixes #337, #338

### LINKED ISSUE #337: change-log still needs some fixes.
```js
/usr/local/bin/git-changelog: line 230: local: -A: invalid option
local: usage: local name[=value] ...

ERROR:  Specified start-tag does not exist!
```
@spacewander @chernjie  Noticing this?

`local -A` is not working on:

```
Darwin Apples-Macintosh.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```

```
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

### PR DESCRIPTION
**Pull request by chernjie**
Removed dependency on real associative arrays, which are not
support previous to bash 4.

cc: @markeissler

### CODE REVIEW

**Comment by spacewander** [comment]
```
$ git  changelog
fatal: ambiguous argument '%D..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Strange...

**Comment by spacewander** [comment]
Oh, the pretty format placeholder '%D' isn't supported in git 1.9.1.
After I upgrade it to latest version, all things go right.

**Comment by markeissler** [comment]
@spacewander You're killing me. I think it would be reasonable to have some minimum requirements. But that would be a project-wide discussion/decision. Perhaps I should just check that a suitable version of git is installed (not sure which one introduces %D) and abort with an error if the installed version is too crusty?

**Comment by spacewander** [comment]
I do a search and find out the '%D' is introduced in v2.2.0.

Don't worry, I will write a workaround based on your code.

**Comment by markeissler** [comment]
@spacewander Is the '%D" issue the only item holding back this PR at the moment?

**Comment by spacewander** [comment]
@markeissler  I have send a [pr](https://github.com/markeissler/git-extras/pull/1) to you, which gets rid of '%D' and adds support for old git version.

@hemanth  What about the latest `git-changlog` ? Is it OK?

**Comment by markeissler** [comment]
@spacewander @hemanth Merged PR. Looks good to me.

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
