### PR TITLE
abort git-alias when too many arguments given.

### PR DESCRIPTION
**Pull request by spacewander**
Avoid incorrect usage probably because of the missing quotes, like "git
alias cm checkout master"

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by nicolaiskogheim** [comment]
This is a good idea.

Maybe we could just print a usage message instead?

**Comment by spacewander** [comment]
Just add a "usage" banner

**Comment by nicolaiskogheim** [comment]
I'm sorry I didn't just do this straight away. I was thinking we should do it like i.e `git rebase` does it.

```sh
error: unknown option `fsjljksldf'
usage: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] [<upstream>] [<branch>]
   or: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] --root [<branch>]
   or: git-rebase --continue | --abort | --skip | --edit-todo

etc..
```

as in

```sh
error: too many arguments
usage: git alias                         # list all aliases
  or: git alias <search-pattern>         # show aliases matching pattern
  or: git alias <alias-name> <command>   # alias a command
```

( I think the comments was nice so I left them in, although git doesn't usually do it that way)

And maybe we should call it `<search-pattern>`, because it is a regex. Then you can edit the man page to say `search-pattern` instead of `search-term` as well.

**Comment by spacewander** [comment]
All right, updated it.

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
