### PR TITLE
Delete branches in all listed remote repositories

### PR DESCRIPTION
**Pull request by hickey**
This pull will look for branches in all of the remote repositories and delete the remote branches, not just origin.

### CODE REVIEW

**Comment by bturrubiates** [comment]
Maybe this should be an option like `--all` instead of the default behavior.

**Comment by hickey** [comment]
Sorry, I have left this alone for far too long......

I have at times found the default nature of deleting the remote branch a hindrance as well as a feature. So the more I think about it, @bturrubiates has the better idea to trigger deleting the remote branch off of a switch. By now this may be in the git-extras code base. So I will close this PR and do badly needed update of my local repo :-)

**Comment by qw3rtman** [comment]
If this were to get implemented, I agree with @bturrubiates that this should not be the default behavior. In my opinion, it's pretty unexpected and may cause problems for the vast majority who is not expecting this kind of behavior.

**Comment by bturrubiates** [comment]
> I have at times found the default nature of deleting the remote branch a hindrance as well as a feature. So the more I think about it, @bturrubiates has the better idea to trigger deleting the remote branch off of a switch. By now this may be in the git-extras code base. So I will close this PR and do badly needed update of my local repo :-)

I don't think it's in the `git-extras` code base yet. I haven't had enough time work up the other PR I was going to do yet, but I could add that to it whenever I get to it. 🎉 



> If this were to get implemented, I agree with @bturrubiates that this should not be the default behavior. In my opinion, it's pretty unexpected and may cause problems for the vast majority who is not expecting this kind of behavior.

It's potentially very dangerous. If it is behind a `--all` switch, then at least `git-extras` is less responsible for causing damage.

**Comment by qw3rtman** [comment]
Agreed, @bturrubiates. Would love to see a PR whenever you get the chance. :smile:

**Pull request closed without merging**
