### PR TITLE
Merge wiki into main repository

### LINKED ISSUE #358: [Discussion] Documentation vs wiki
### TL;DR
Documentation should be in the same git repo as it's main project

### Long version
I understand `git-extras` have recently moved the long winded contents of `Readme.md` into Github's wiki. It is a good thing as `Readme.md` has become too long and at some point has become difficult to maintain.

Having said that, I do think that the `HEAD` of each wiki ref should stay in sync with the `HEAD` of each pull request. This ensures that documentations are not left out and encourage script discovery.

@hemanth has been tirelessly advising pull requesters to update the wiki on every successful review. Perhaps we could be suggested that unless documentations are updated, the PR will not be merged?

### Proposed solution (simple)
Since Github's wiki is also a Git repo, we can merge it into the main repo without losing history or `refheads`. Effectively retiring Github wiki.

What are your thoughts on this?

### PR DESCRIPTION
**Pull request by chernjie**
Closes #358 

### TL;DR
Documentation should be in the same git repo as it's main project

### Long version
I understand `git-extras` have recently moved the long winded contents of `Readme.md` into Github's wiki. It is a good thing as `Readme.md` has become too long and at some point has become difficult to maintain.

Having said that, I do think that the `HEAD` of each wiki ref should stay in sync with the `HEAD` of each pull request. This ensures that documentations are not left out and encourage script discovery.

@hemanth has been tirelessly advising pull requesters to update the wiki on every successful review. Perhaps we could be suggested that unless documentations are updated, the PR will not be merged?

### Proposed solution (simple)
Since Github's wiki is also a Git repo, we can merge it into the main repo without losing history or `refheads`. Effectively retiring Github wiki.

### Follow up task
- [ ] update wiki

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by hemanth** [comment]
Ping @chernjie

**Comment by chernjie** [comment]
Oh sorry, I missed your message.

By "updating wiki", I mean to delete all the contents there. Are you okay with that?

For release, yes you can merge this. We can always update the wiki later.

**Comment by hemanth** [comment]
Just like back to the readme in wiki would be good, as people might go to wiki to read the docs, I'll merge this for now, Thank you!

**Comment by hemanth** [comment]
Just like back to the readme in wiki would be good, as people might go to wiki to read the docs, I'll merge this for now, Thank you!

**Comment by chernjie** [comment]
Wiki updated with the relevant links :)

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
