### PR TITLE
Add git-abort

### PR DESCRIPTION
**Pull request by pkitszel**
New subcommand just calls git $op --abort, where $op is current git operation, like rebase

### CODE REVIEW

**Comment by pkitszel** [comment]
Hi,

my proposed command is really useful for me, despite being so simple :) 
If this PR would be accepted, I will submit another one with similar git-continue ;) (too bad, that symlinks support is not great in git...).

PK

**Comment by bl-ue** [comment]
ping @spacewander looks cool, could you please merge?

@pkitszel there are merge conflicts, could you please fix those?

**Review by bl-ue — APPROVED** [review]

**Comment by spacewander** [comment]
I will take a look after the conflict is solved.

**Comment by pkitszel** [comment]
@spacewander, I have resolved the conflict.

**Review by spacewander — APPROVED** [review]

**Pull request merged**
