### PR TITLE
Fix some fatal for git-line-summary

### PR DESCRIPTION
**Pull request by zlx**
1. print format when exist special characters
2. special characters in git blame output
3. exist not committed new files will raise `fatal: no such path 'newfilename' in HEAD`

### CODE REVIEW

**Comment by hemanth** [comment]
@zix Thanks! Could you please squash the commits?

**Comment by zlx** [comment]
@hemanth of cause!

**Comment by hemanth** [comment]
:+1:

**Comment by zlx** [comment]
Nice. Thank you

**Pull request merged**
