### PR TITLE
Update git PR manual to mention URLs

### PR DESCRIPTION
**Pull request by rstacruz**
Happy to see git-pr now supports URLs, thanks @jhnns! This documents that.

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by nicolaiskogheim** [comment]
I might be missing out on something, but why is the html-page removed?

**Comment by rstacruz** [comment]
oops, no idea, whats just what `ronn` did

**Comment by jhnns** [comment]
Sorry for not also updating the manual :grin:. I thought it would be sufficient to update `Commands.md`.

**Pull request merged**
