### PR TITLE
Git clear

### PR DESCRIPTION
**Pull request by grindhold**
git-clear is like git reset --hard  but it also removes all untracked files that reside inside the working directory. Clears the repo as if it was freshly cloned at the current HEAD-commit.

### CODE REVIEW

**Comment by spacewander** [comment]
IMHO, we can do the same thing with an alias:
```
alias gclear="git clean -d -f -x && git reset --hard"
```

**Comment by hemanth** [comment]
Yes, that looks better, btw we add such one liners to http://git.io/git-tips ;)

**Comment by grindhold** [comment]
ok

**Comment by hemanth** [comment]
@grindhold Hold! We didn't mean to close the PR, we can have `git clean -d -f -x && git reset --hard` instead of [this](https://github.com/tj/git-extras/pull/433/files#diff-027e63237a1ce78ab40f11082c9fc6c3R4) what say @spacewander ?

**Comment by grindhold** [comment]
ah okay, i presumed git-clear was kind of too simple and obvious to be included into git extras ;)

**Comment by grindhold** [comment]
i use the command from above to implement git-clear now.

**Comment by hemanth** [comment]
LGTM @spacewander what say?

**Comment by spacewander** [comment]
Maybe a clearer prompt will be better.
"Sure?" is not easy to understand in a glance, we need to tell  the user what this command will do.

**Comment by grindhold** [comment]
@spacewander now it's a more understandable question

**Comment by spacewander** [comment]
Good job.

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
