### PR TITLE
Fix 502

### LINKED ISSUE #502: changelog does not work if GIT-EDITOR contains spaces
My git editor is set to 

```
λ git var GIT_EDITOR
"C:\Program Files (x86)\Notepad++\notepad++.exe"  -multiInst -nosession -noPlugin
```

This results in the following error during a git changelog call:

```
λ git changelog
C:\Program Files\Git\mingw64\bin\git-changelog: line 490: "C:\Program: No such file or directory

caught signal, shutting down
C:\Program Files\Git\mingw64\bin\git-changelog: line 342: pgrep: command not found
```

Additionally, it seems that `pgrep` is not available in git for windows :-(

### PR DESCRIPTION
**Pull request by spacewander**
Wrap GIT_EDITOR and replace pgrep
Hope it can fix #502

### CODE REVIEW

**Comment by JanSchulz** [comment]
This still doesn't work:

```
λ git changelog
/tmp/git-changelog.yod History.md
C:\Program Files\Git\mingw64\bin\git-changelog: line 492: "C:\Program Files (x86)\Notepad++\notepad++.exe"  -multiInst -nosession -noPlugin: No such file or directory

caught signal, shutting down
ps: unknown option -- o
Try `ps --help' for more information.
```

```
λ ps --help
Usage: ps [-aefls] [-u UID] [-p PID]

Report process status

 -a, --all       show processes of all users
 -e, --everyone  show processes of all users
 -f, --full      show process uids, ppids
 -h, --help      output usage information and exit
 -l, --long      show process uids, ppids, pgids, winpids
 -p, --process   show information for specified PID
 -s, --summary   show process summary
 -u, --user      list processes owned by UID
 -V, --version   output version information and exit
 -W, --windows   show windows as well as cygwin processes

With no options, ps outputs the long format by default
```

This is the output of a `ps -e` directly before the failing line in `_exit`:

```
λ git changelog
C:\Program Files\Git\mingw64\bin\git-changelog: line 491: "C:\Program Files (x86)\Notepad++\notepad++.exe"  -multiInst -nosession -noPlugin: No such file or directory

caught signal, shutting down
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     9596       1    9596       8616  cons0     197611 09:18:33 /usr/bin/bash
     7160    9596    9596      11116  cons0     197611 09:18:33 /usr/bin/ps
     7612       1    7612       7612  ?         197611   Jan 13 /usr/bin/ssh-agent
ps: unknown option -- o
Try `ps --help' for more information.
```

Re the editor: the interesting thing is that it seems the quotes are there:

```
λ git changelog
C:\Program Files\Git\mingw64\bin\git-changelog: line 491: "C:\Program: No such file or directory
                                                          ^
```

**Comment by JanSchulz** [comment]
Hah, this works: `    [[ -n "$GIT_EDITOR" ]] && eval $GIT_EDITOR "$changelog"`

**Comment by spacewander** [comment]
@JanSchulz 
Thanks for your solution, I just submitted new change to my former pr. Now I am trying to solve the issue #504 together...

**Comment by JanSchulz** [comment]
Just FYI: I tested this PR and it works on windows. So +1 for merging...

**Comment by hemanth** [comment]
Thank you @spacewander @JanSchulz .

**Pull request merged**
