### PR TITLE
Update git-standup command

### PR DESCRIPTION
**Pull request by Ethenyl**
The `git-standup` module is out-of-date, so I updated the command file & copied the official documentation.

### CODE REVIEW

**Comment by Ethenyl** [comment]
Woops sorry for closing the PR... I thought I was still in my fork.

**Comment by spacewander** [comment]
```
$ ./git-standup spacewander "last week"
Invalid arguments: spacewander last week
Use 'git standup -h' to see usage info
```

Well, breaking change is not so welcome, unless it is a bugfix.
Maybe you can find a way to support both old arguments and the new ones? No one likes `update and then something breaks down suddenly`.

**Comment by Ethenyl** [comment]
The newest version of `git-standup` does break old arguments but it's an official behaviour.

So who's responsibility is it to fix this ? I'm not the main developer of `git-standup` and I might break a thing or two by trying to implement old arguments & new arguments.

I'm willing to take the chance but for me it's more an issue like `switching from Swift 2.2 to Swift 3.0 broke down a lot of things but nothing we can do about it`.

**Comment by spacewander** [comment]
@Ethenyl 
Admittedly, support old arguments and new ones at the same time is hard. But it still worths a try.
Swift is not a good role model. I have heard many complaints to its stability, and don't want to see this happened on `git-extras`.
Don't say `I can't do it` before trying hard.

**Comment by Ethenyl** [comment]
@spacewander
It's not a matter of `it's too hard` or `I can't do it`, as I said, I'm more than willing to try to add the old arguments.

What I am asking is, does it make sense to mix both old & new arguments together?

I don't recall any script / command that keeps 'deprecated' arguments alongside new arguments.

The author of `git-standup` changed the 'paradigm' of his script so should we follow the new orientation & forget about old ways?

BTW I mentioned **Swift** as an exemple, the same thing happened with **AngularJS** and some other open-sourced frameworks / languages.

**Comment by troystevenhunt** [comment]
￦￦￦[°°°20|20····]>>>¥¥¥Ω©©💶💷💴💵📱📡💿📀❄💣💣💣💣💣🔋🔋🔋🔋🔋🔋🔋🔋📡

On Dec 7, 2016 2:16 AM, "Damien R." <notifications@github.com> wrote:

@spacewander <https://github.com/spacewander>
It's not a matter of it's too hard or I can't do it, as I said, I'm more
than willing to try to add the old arguments.

What I am asking is, does it make sense to mix both old & new arguments
together?

I don't recall any script / command that keeps 'deprecated' arguments
alongside new arguments.

The author of git-standup changed the 'paradigm' of his script so should we
follow the new orientation & forget about old ways?

BTW I mentioned *Swift* as an exemple, the same thing happened with
*AngularJS* and some other open-sourced frameworks / languages.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tj/git-extras/pull/605#issuecomment-265395653>, or mute
the thread

**Comment by Ethenyl** [comment]
@troystevenhunt I'm sorry, I don't get it. Care to explain this flow of Emoticons ?

**Comment by Ethenyl** [comment]
Hi @spacewander,

Still waiting on your feedback concerning the complete change of parameters from the creator of `git standup`.

Should I close my PR or should I try to do something else ?

Thanks in advance for your feedback on this topic.

_P.S : I might need to update my PR, the script might have changed since december..._

**Comment by spacewander** [comment]
@Ethenyl 
Could you support both new arguments and old arguments the same time, let the update be painless?

**Pull request closed without merging**
