### PR TITLE
git scp - Copy files to SSH compatible `git-remote`

### PR DESCRIPTION
**Pull request by chernjie**
### git-scp(1) -- Copy files to SSH compatible `git-remote`

A convenient way to copy files from the current working tree to the working directory of a remote repository. If a `<commits>...` is provided, only files that has changed within the commit range will be copied.

Internally this script uses `rsync` and not `scp` as the name suggests. 

`git-rscp` - Copies specific files from the working directory of a remote repository to the current working directory.

----

### TODO
1. [x] write `man/git-scp.md`
2. [x] generate man files via `ronn`
3. [x] symlink `git-rscp` to `git-scp`
4. [x] Add `bash_completion`

### CODE REVIEW

**Comment by hemanth** [comment]
@chernjie Awesome, only `symlink` remains.

**Comment by chernjie** [comment]
@hemanth I need help testing if the symlink works during installation, can you help?

**Comment by chernjie** [comment]
@hemanth I have managed to test the symlink, this is good to merge :)

**Comment by hemanth** [comment]
Awesome! Thanks.

**Comment by hemanth** [comment]
@chernjie Could you please update the wiki?

**Pull request merged**
