### PR TITLE
Make git effort run on FreeBSD

### LINKED ISSUE #402: git effort errors out with bash errors on FreeBSD 10.1
Hi,

running `git effort` yields this:

      file                                          commits    active days

    bash: Skipping importing function definition for `effort': --import-functions required.
    bash: Skipping importing function definition for `active_days': --import-functions required.
    bash: Skipping importing function definition for `date': --import-functions required.
    bash: Skipping importing function definition for `color_for': --import-functions required.
    bash: Skipping importing function definition for `effort': --import-functions required.
    bash: Skipping importing function definition for `active_days': --import-functions required.
    bash: Skipping importing function definition for `date': --import-functions required.
    bash: Skipping importing function definition for `color_for': --import-functions required.
    bash: effort: command not found
…
repeated oftentimes, depending on repository size.

    GNU bash, version 4.3.39(2)-release (amd64-portbld-freebsd10.1)

### PR DESCRIPTION
**Pull request by nicolaiskogheim**
This should fix #402

@yggdr

### CODE REVIEW

**Comment by nicolaiskogheim** [comment]
Hold on a sec, I messed up the commit message there.

**Comment by yggdr** [comment]
This version is now works in principle, but seems to have problems with tracked files with spaces in their names (missing quotation?), and outputs a lot of lines that seem empty at first glance, but are actually just the exact colour of my background :(

**Comment by nicolaiskogheim** [comment]
I have seen that color problem before. The darkest colors from `git effort` is the same as the background color for Solaris-themed terminals.

I'll test for files with spaces.

**Comment by nicolaiskogheim** [comment]
So, I suggest we merge in this one, and take it from there.

Quoting and coloring are separate issues that affects everyone, not just FreeBSD.

@hemanth

**Comment by hemanth** [comment]
Makes sense.

**Pull request merged**
