### PR TITLE
How to update a submodule version to latest ?

### PR DESCRIPTION
**Pull request by manobi**
I always have to do this, there are a better way ?

### CODE REVIEW

**Comment by kshcherban** [comment]
The other way to update submodule which tracks branch is:

```
git pull --recurse-submodules
git submodule update --remote --recursive
```

**Comment by hemanth** [comment]
Sorry for missing this! 

@manobi Still interested to complete this?

If not any of you guys want to paw at it?

**Comment by FelikZ** [comment]
@kshcherban the best way, thanks!

**Comment by hemanth** [comment]
@spacewander Looks like we must bring in this?

**Comment by spacewander** [comment]
So, what name should we use for it?

`update-submodule` or `merge-submodule` or others?

**Comment by FelikZ** [comment]
pull-submodule?

**Comment by hemanth** [comment]
`merge-submodule` sound good if `fetch` and  `merge` we could name it `pull-submodule`?

**Comment by spacewander** [comment]
Ok， so name it as `pull-submodule`. I will try to dive into it this weekend.

**Comment by hemanth** [comment]
:+1:

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by kornvigo** [comment]
pull-submodule?

**Comment by RobLoach** [comment]
The following command will update all submodules to the latest `branch` that's defined in `.gitmodules`...
```
git submodule update --recursive --remote
```

```
[submodule "my/module"]
	path = my/module
	branch = master
```

**Comment by MarceloMelo1** [comment]
`git submodule foreach git pull origin master`

**Comment by DreamAndDead** [comment]
```
git submodule update --remote
```

**Pull request closed without merging**
