### PR TITLE
pass tag and optional arguments to hook and stop if pre-release hook fails

### LINKED ISSUE #650: Stop release if pre-release hook fails
`git release 1.0.0` does not fail even if pre-release hook exits with error. It should continue with release if pre-release hook fails.

### PR DESCRIPTION
**Pull request by spacewander**
This pr is based on the work done in #192.
It is expected to fix #650 and other problem.

@breneser
Could you give this branch a try, and confirm whether the problems are fixed?

### CODE REVIEW

**Comment by breneser** [comment]
@spacewander Seems to be working just fine. A message on pre-release failure would be more descriptive IMHO. Something like "pre-release hook failed! Cancelling release"

Takes for taking time to implement this.

**Comment by spacewander** [comment]
@breneser 
Just add a notification for `pre-release` hook.
Would you like to try it again?

**Comment by breneser** [comment]
@spacewander Yes, this works very nicely. Only one thing though, I think message should be written to stderr rather than stdout ?

**Comment by spacewander** [comment]
@breneser 
My thoughless. Now the message will be sent to stderr.

**Comment by breneser** [comment]
@spacewander Great, thanks :)

**Comment by breneser** [comment]
@spacewander any idea when this would be merged in ?

**Pull request merged**
