### PR TITLE
Fixes #332 git show-merged-branches and show-unmerged-branches

### LINKED ISSUE #332: git show-merged-branches and show-unmerged-branches
It would be nice to have git show-merged-branches and show-unmerged-branches commands.

### PR DESCRIPTION
**Pull request by paulschreiber**

### CODE REVIEW

**Comment by hemanth** [comment]
@paulschreiber Could you please squash the commits?

**Comment by paulschreiber** [comment]
How do you want me to do that? Make a new branch/PR?

**Comment by hemanth** [comment]
No, just squash in the same branch.

**Comment by paulschreiber** [comment]
Done.

**Comment by hemanth** [comment]
Cool, thanks! 

Please don't forget to update the wiki.

**Pull request merged**
