### PR TITLE
feat: add ruff linter with ci check

### PR DESCRIPTION
**Pull request by oikarinen**
Linting the python files in tests directory would reduce whitespace etc change and enforce basic coding standard for those. Kind of opportunistic PR as there might be other opinions about how to deal with this.

### CODE REVIEW

**Comment by spacewander** [comment]
Let's merge main branch.

**Review by spacewander — APPROVED** [review]

**Comment by spacewander** [comment]
@vanpipy 
Please take a look if you have free time.

**Review by hyperupcall — APPROVED** [review]
LGTM. These changes are somewhat moot as at some point in the future, the tests will transition from using Python's Pytest to Bash's BATS testing framework

**Comment by vanpipy** [comment]
LGTM. At least for now. Thank you so much :D.

**Review by vanpipy — APPROVED** [review]

**Pull request merged**
