### PR TITLE
add git-revive

### PR DESCRIPTION
**Pull request by rhacker**
Add git revive to restore deleted file based on file_path

### CODE REVIEW

**Comment by nicolaiskogheim** [comment]
This looks like i could be a nice feature.

@rhacker, planning on completing this?

**Comment by nicolaiskogheim** [comment]
I want to complete this, but I think I want to call it `git restore`.

**Comment by rhacker** [comment]
@nicolaiskogheim Do as you please :)

**Comment by hemanth** [comment]
:+1:

**Pull request closed without merging**
