### PR TITLE
Fix integrity for git-reauthor

### PR DESCRIPTION
**Pull request by spacewander**
I plan to add travis-ci for integrity check later.

### CODE REVIEW

**Comment by spacewander** [comment]
Anything else shall we check in the ci?
@hemanth @nicolaiskogheim @qw3rtman

**Comment by hemanth** [comment]
LGTM

**Comment by nicolaiskogheim** [comment]
The `check-integrity.sh` is good for now.

It would be interesting to see what versions of bash, and possibly sh that our scripts work with, though. If it's easy to test against multiple versions, we should do that.

**Comment by spacewander** [comment]
Just add travis CI configure file.
Now we have a little CI!

**Comment by nicolaiskogheim** [comment]
A good start! LGTM

**Comment by qw3rtman** [comment]
LGTM!

**Comment by spacewander** [comment]
@tj 
Could you enable the travis ci here: https://travis-ci.org/tj/git-extras?
Thanks!

**Comment by tj** [comment]
enabled!

**Comment by qw3rtman** [comment]
Thanks, @tj!

**Pull request merged**
