### PR TITLE
Fix deleting branches without upstream

### PR DESCRIPTION
**Pull request by MontakOleg**
See https://github.com/tj/git-extras/issues/705 for details

### CODE REVIEW

**Comment by spacewander** [comment]
@MontakOleg 
Maybe we could use `git config branch.$branch.remote || echo 'origin'` and `git branch -D ... || continue` to achieve the same result, without removing the `set -e`?

**Comment by MontakOleg** [comment]
I will try

**Comment by MontakOleg** [comment]
`git branch -D ... || continue` will skip deleting remote branch, if local branch does not exists. This is expected behavior?

And what we want to do if `git branch -d -r $remote/$branch` fails?


I would prefer to try delete remote branch even if there no local branch.

**Comment by spacewander** [comment]
@MontakOleg 
Well, we could use `git branch -D ... || true` instead?
In my opinion, we could use  `|| continue` with `git branch -d -r $remote/$branch`. If we failed to delete the remote tracking branch locally, we don't need to push the change to the remote.

**Comment by MontakOleg** [comment]
@spacewander
Look at this, please.

**Comment by spacewander** [comment]
@MontakOleg 
Merged. Thank you!

**Pull request merged**
